import type { GetServerSideProps, GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import Home from './home/index.page';
import { getComics } from 'dh-marvel/services/marvel/marvel.service';
import { Comic } from 'model/comic';
import { useState } from 'react';
import { Button } from '@mui/material';
import { useRouter } from 'next/router';
import { Params } from 'next/dist/shared/lib/router/utils/route-matcher';

interface Props {
    comics: Comic[];
}

const Index: NextPage<Props> = ({comics}) => {

    const router = useRouter();
    const cant = 12;
    const [offset, setOffset] = useState(0);

    const handleOffsetChange = (newOffset: number) => {
        setOffset(newOffset);
        router.push(`/?offset=${newOffset}`)
    }

    return (
        <>
            <Head>
                <title>Comic Store</title>
                <meta name="Comics" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BodySingle title={"Comics"}>
                <Home comics={comics}/>
                {offset != 0 &&
                    <Button onClick={() => handleOffsetChange(offset - cant)}>Anterior</Button>
                }
                <Button onClick= {() => handleOffsetChange(offset + cant)}>Siguiente</Button>
            </BodySingle>
        </>
    )
}

    
export const getServerSideProps: GetServerSideProps<Props> = async ({params}) => {

    const offset = params?.offset || '0';

    const comics = await getComics(parseInt(offset as string), parseInt(offset as string) + 12);   
    
    return {
      props: {
        comics: comics.data.results
      }
    };
  };


export default Index
